name: Deploy to AWS EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Instalar SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy na EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
        cd /home/ec2-user/seu-projeto
        sudo yum install git -y
        git pull origin main
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart gunicorn  # Substitua pelo nome correto do serviço
        EOF
